sudo: false

language: php

matrix:
  include:
    - name: '[REQUIRE_CHECK] With Locked Dependencies'
      php: '7.3'
      env: require=1
    - name: '[REQUIRE_CHECK] With Lowest Dependencies'
      php: '7.3'
      env: require=1 dependencies=lowest
    - name: '[REQUIRE_CHECK] With Highest Dependencies'
      php: '7.3'
      env: require=1 dependencies=highest

    - name: '[CS] PHP 7.2 With Locked Dependencies'
      php: '7.2'
      env: cs=1
    - name: '[CS] PHP 7.2 With Lowest Dependencies'
      php: '7.2'
      env: cs=1 dependencies=lowest
    - name: '[CS] PHP 7.2 With Highest Dependencies'
      php: '7.2'
      env: cs=1 dependencies=highest
    - name: '[CS] PHP 7.3 With Locked Dependencies'
      php: '7.3'
      env: cs=1
    - name: '[CS] PHP 7.3 With Lowest Dependencies'
      php: '7.3'
      env: cs=1 dependencies=lowest
    - name: '[CS] PHP 7.3 With Highest Dependencies'
      php: '7.3'
      env: cs=1 dependencies=highest
    - name: '[CS] PHP Nightly With Locked Dependencies'
      php: nightly
      env: cs=1
    - name: '[CS] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: cs=1 dependencies=lowest
    - name: '[CS] PHP Nightly With HIghest Dependencies'
      php: nightly
      env: cs=1 dependencies=highest

    - name: '[UNIT] PHP 7.2 With Locked Dependencies'
      php: '7.2'
    - name: '[UNIT] PHP 7.2 With Lowest Dependencies'
      php: '7.2'
      env: dependencies=lowest
    - name: '[UNIT] PHP 7.2 With Highest Dependencies'
      php: '7.2'
      env: dependencies=highest
    - name: '[UNIT] PHP 7.3 With Locked Dependencies'
      php: '7.3'
    - name: '[UNIT] PHP 7.3 With Lowest Dependencies'
      php: '7.3'
      env: dependencies=lowest
    - name: '[UNIT] PHP 7.3 With Highest Dependencies'
      php: '7.3'
      env: dependencies=highest
    - name: '[UNIT] PHP Nightly With Locked Dependencies'
      php: nightly
    - name: '[UNIT] PHP Nightly With Highest Dependencies'
      php: nightly
      env: dependencies=lowest
    - name: '[UNIT] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: dependencies=highest
  allow_failures:
    - name: '[CS] PHP Nightly With Locked Dependencies'
      php: nightly
      env: cs=1
    - name: '[CS] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: cs=1 dependencies=lowest
    - name: '[CS] PHP Nightly With HIghest Dependencies'
      php: nightly
      env: cs=1 dependencies=highest

    - name: '[UNIT] PHP Nightly With Locked Dependencies'
      php: nightly
    - name: '[UNIT] PHP Nightly With Highest Dependencies'
      php: nightly
      env: dependencies=lowest
    - name: '[UNIT] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: dependencies=highest

before_install:
- phpenv config-rm xdebug.ini || echo "No xdebug config."
- composer self-update

install:
- wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar
- chmod +x php-coveralls.phar

before_script:
  - if [ -z "$dependencies" ]; then travis_retry composer install --no-scripts; fi;
  - if [ "$dependencies" = "lowest" ]; then travis_retry composer update --no-scripts --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then travis_retry composer update --no-scripts -n; fi;

script:
  - if [ -z "$cs" ] && [ -z "$require" ]; then phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml; fi;
  - if [ "$cs" = 1 ]; then vendor/bin/phpcs -s; fi;
  - if [ "$require" = 1 ]; then vendor/bin/composer-require-checker check; fi;

after_success:
  - if [ -z "$cs" ] && [ -z "$require" ]; then travis_retry php php-coveralls.phar; fi;
